version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - app-network
    # Para desarrollo, descomenta estas líneas:
    # volumes:
    #   - ./client:/app
    #   - /app/node_modules

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    networks:
      - app-network
    # Para desarrollo, descomenta estas líneas:
    # volumes:
    #   - ./server:/app
    #   - /app/node_modules

networks:
  app-network:
    driver: bridge