version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Cambiado a 3000 que es el puerto por defecto de Vite
    environment:
      - VITE_API_URL=http://server:5000
    depends_on:
      - server
    networks:
      - app-network
    # Para desarrollo, descomenta estas líneas:
    # volumes:
    #   - ./client:/app
    #   - /app/node_modules

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DATABASE_URL=postgresql://postgres:${DB_PASSWORD}@postgres:5432/userdb
      - DATABASE_URL_DB2=postgresql://postgres:${DB2_PASSWORD}@postgres_db2:5433/authdb
    depends_on:
      - postgres
      - postgres_db2
    networks:
      - app-network
    # Para desarrollo, descomenta estas líneas:
    # volumes:
    #   - ./server:/app
    #   - /app/node_modules

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: userdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  postgres_db2:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB2_PASSWORD}
      POSTGRES_DB: authdb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_auth:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  postgres_data_auth: