version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Cambiado a 3000 que es el puerto por defecto de Vite
    environment:
      - VITE_API_URL=http://server:5000
    depends_on:
      - server
    networks:
      - app-network
    # Para desarrollo, descomenta estas líneas:
    # volumes:
    #   - ./client:/app
    #   - /app/node_modules

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/pepedb
      - NODE_ENV=development
    depends_on:
      - postgres
    networks:
      - app-network
    # Para desarrollo, descomenta estas líneas:
    # volumes:
    #   - ./server:/app
    #   - /app/node_modules

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pepedb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: