FROM node:20-alpine

WORKDIR /app

# Copiar archivos de configuración
COPY package*.json ./

# Instalar dependencias incluyendo devDependencies
RUN npm install

# Copiar el resto del código
COPY . .

# Exponer puerto
EXPOSE 5000

# Comando para iniciar en modo desarrollo
CMD ["sh", "-c", "npx prisma generate && npm run dev"]