FROM node:18-alpine

WORKDIR /app

# Copiar archivos de configuración
COPY package*.json ./
COPY prisma ./prisma/

# Instalar dependencias y generar Prisma Client
RUN npm install
RUN npx prisma generate --schema=./prisma/schema.prisma
RUN npx prisma generate --schema=./prisma/schema2.prisma

# Copiar el resto del código
COPY . .

# Exponer puerto
EXPOSE 5000

# Comando para iniciar en modo desarrollo
CMD ["sh", "-c", "npm run prisma:push && npm run dev"]