FROM node:20-alpine

WORKDIR /app

# Install dependencies
RUN apk add --no-cache libc6-compat openssl

# Copy package files and prisma schema
COPY package*.json ./
COPY prisma ./prisma/

# Install dependencies
RUN npm install

# Clean Prisma cache
RUN rm -rf node_modules/.prisma

# Generate Prisma Client
RUN npx prisma generate

# Copy rest of the application
COPY . .

EXPOSE 5000

# Start the application
CMD ["npm", "run", "dev"]